### ISSUE TITLE
Why to fragment projects? Why not to merge pdfminer.six into original pdfminer?

### ISSUE THREAD

**Issue by KOLANICH** [pdfminer/pdfminer.six#111]
I mean that I see no reason to have pdfminer.six separate from pdfminer. I wonder why such a decision has been made?
https://github.com/euske/pdfminer/issues/210

**Comment by ganeshtata** [comment]
Hi @KOLANICH. I am not really sure, but I think that the original pdfminer is largely unmaintained. Since the maintainer has not been active, there was no way for people to keep contributing to it. Thus, this fork is still a separate project.

**Comment by KOLANICH** [comment]
Maintainer is active, he is alive and making commits ... into other repos. So he is alive, he is subscribed to all the activity so he sees our PR's and issues. So I guess it should not be a very big deal for him to merge this fork and to transfer ownership of the main repo to the org.

**Comment by ganeshtata** [comment]
@KOLANICH I am well aware of the fact that the maintainer is "alive". Sure. We can raise an issue in the original pdfminer for the same.

**Comment by KOLANICH** [comment]
>We can raise an issue in the original pdfminer for the same.

I have already done that.

**Comment by goulu** [comment]
Hi there. originally I forked pdfminer because I needed it in a Python 3, and @euske didn't want to support Python 3 ( https://github.com/euske/pdfminer/issues/63 )

I nevertheless sent .six as a push request  https://github.com/euske/pdfminer/pull/71 which was declined.

So unless @euske changes his mind and becomes more active, I believe the way to continue is to merge his branch into this one.

If you want to help, you're welcome : we can add you to the group, give you credentials for PyPi. Just ask.

Once again I apologize for not being more active on this project : I did it just because I needed it for something specific, which is now done.

**Comment by KOLANICH** [comment]
>If you want to help, you're welcome : we can add you to the group, give you credentials for PyPi.

Thank you for suggestion, but no, I'm not going to maintain and develop it in long scale, so there is no need to give me, a stranger, credentials. But in near future there probably will be PRs from me.
