### ISSUE TITLE
how can I ignore the formulas?

### ISSUE THREAD

**Issue by leolle** [pdfminer/pdfminer.six#140]
I am converting a Chinese file with formulas, which are not well supported. 

The converted text from formulas are mess. Is there an option that can ignore those formulas or headers?

Thanks.

**Comment by ganeshtata** [comment]
Hi @leolle. Is it possible for you to provide an example PDF?

**Comment by leolle** [comment]
https://drive.google.com/file/d/1bqH_6g077IZdkcweQl8M8b029EA_Ni_r/view?usp=sharing
@ganeshtata

**Comment by RolandColored** [comment]
unfortunately this file is not public.

**Comment by pquentin** [comment]
@RolandColored I can see it without any problems, even without being connected to a Google account

**Comment by leolle** [comment]
@RolandColored can you use another browser like Chrome?

**Comment by RolandColored** [comment]
Surprisingly it worked when I logged off from Chrome. Maybe my work account is too restrictive. 😄

**Comment by pietermarsman** [comment]
There is no generic way in pdfminer.six to ignore formulas. This is because the formulas are made up of the same building blocks as the rest of the pdf: characters, lines and other geometrical shapes. 

If you have a specific pdf in mind you could check the fontsize or the font type, maybe these are different for the formulas.
