### ISSUE TITLE
JPXDecode error

### ISSUE THREAD

**Issue by bashkirtsevich** [pdfminer/pdfminer.six#163]
Hello, I have a problem with pdf image extraction. When I invoke `stream.get_data()`, library says, that she doesnt supports `JPXDecode` filter (not implemented). How I can avoid or fix this bug? I need image data.

**Comment by RolandColored** [comment]
You could "just" extend the list of decoders here:
https://github.com/euske/pdfminer/blob/44977b6726640933d86028d16ca06fab5ea26d1a/pdfminer/pdftypes.py#L263

Since there is no decoding necessary, it's sufficient to return the stream. PyPDF does it in the same way:
https://github.com/mstamy2/PyPDF2/blob/18a2627adac13124d4122c8b92aaa863ccfb8c29/PyPDF2/filters.py#L353

**Comment by ganeshtata** [comment]
@bashkirtsevich  Has the solution proposed by @RolandColored  worked for you?

**Comment by bashkirtsevich** [comment]
@ganeshtata, is this library alive? Developers can fix this?

**Comment by pietermarsman** [comment]
Fixed in 708dd20 and #645
