### ISSUE TITLE
Extracting Greek alphabet from pdf

### ISSUE THREAD

**Issue by remondulos** [pdfminer/pdfminer.six#188]
Not an issue but a question. When parsing PDF files that contain Greek symbols, pdfminer will translate some symbols to normal alphabet letters. 

For example:
The alpha symbol is translated into 'a' and the gamma symbol is translated into 'c'.

Is there a way to extract these symbols into Unicode characters to identify these symbols?

**Comment by pietermarsman** [comment]
Hi @remondulos, 

Is this problem still relevant for you? Could you maybe add an example pdf that shows this behavior? 

I expect that the PDF specifies that the unicode value of the greek symbols are the latin (normal) alphabet characters. And thus there is not much we can do. But without an example PDF there is no way to tell if this is indeed the case.

**Comment by pietermarsman** [comment]
Closing this as not reproducible (missing pdf).

**Comment by Emasoft** [comment]
This is an issue for me too.
Here is an example PDF that shows this behaviour:

[philo.pdf](https://github.com/pdfminer/pdfminer.six/files/10416774/philo.pdf)

For example, this text:
![IMG_0846](https://user-images.githubusercontent.com/713559/212458876-47c4fe7c-6e92-4135-891a-203b8c0053ac.jpeg)

Is extracted as:
```
phrases such as Aristotle’s ‘mathematical harmonics’ (ἁqlomijὴ ἡ
lahglasijή, An. post. 79a1) and ‘arithmetical harmonicists’ (oἱ
jasὰsoὺ1 ἀqihloὺ1 ἁqlomijoί, Top. 107a15–16).3
```

I also noted that the number for the notes are not extracted correctly, making reading difficult. For example "3" is parsed as a normal number 3 instead of a superscript (" ³ ", unicode U+00B3). Maybe there is an underlying issue with the fonts characters map handling by PDFMiner that causes both those errors?
