### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by KOLANICH** [pdfminer/pdfminer.six#194]
https://python3statement.org

**Comment by ZanonEdoardo** [comment]
I ask to matain this support if possible. Actually i work on 2.7 like many other people.

**Comment by KOLANICH** [comment]
@ZanonEdoardo In my experience 2to3 + some minor manual fixes are usually enough.

I don't want to support this damn legacy, and the only way to make people drop it is to make them start using py3 themselves. And there are 2 complement ways to do that:
* the carrot: make the libs they use compatible with py3, so they can use the better language without additional effort. I do it sending PR's, it's almost free for me since I use python 3 exclusively and I have to port the incompatible libs anyway.
* the stick: make the libs they use incompatible with py2. Again completely free for me. I just write on python 3 and this makes my code incompatible with python 2.

The problems appear when I have to contribute to the repo which policy is to maintain py2 support...

**Comment by hugovk** [comment]
Here's the pip installs for pdfminer.six from PyPI for September 2018:

| Python   | percent | downloads |
|----------|--------:|----------:|
|        3 |  86.29% |    35,515 |
|        2 |  12.45% |     5,125 |
| null     |   1.26% |       517 |
| Total    |         |    41,157 |

**Comment by panoptikum** [comment]
I second this.

**Comment by ZanonEdoardo** [comment]
Ok, With this data you have all reason for remove py2 support.

**Comment by KOLANICH** [comment]
>Ok, With this data you have all reason for remove py2 support.

IMHO the problem is not popularity.  I mean if something is needed only by minority it doesn't mean that one needs to discard it only because of that. One needs more serious reasons, like "it is harmful" or "it doesn't allow us to use new features" or "I personally don't want to put a burden on myself".

**Comment by ganeshtata** [comment]
Can someone point out how we can go about dropping python 2 entirely?

**Comment by KOLANICH** [comment]
>Can someone point out how we can go about dropping python 2 entirely?

1. announce the drop date
2. create a separate python 2 version by stripping all `six` and replacing them with built in stuff
3. create a PR merging that version into `euske` repo
4. start accepting PRs incompatible with python 2
5. remove all the `six` from the version from this repo

**Comment by gwk** [comment]
Hi everyone, that's me. I would love to hear from the community about interest in this. The short version is:
* I ran everything through 2to3.
* I ported the tests to my own test framework, iotest, which is hosted at github/gwk/pithy. The main reason for this is that it does complete output test/diff and so I was able to port the ad hoc tests in the makefiles. I need to work through installation/versioning issues to make this easy for anyone to run, but I am very committed to that project so just let me know what you run into.
* I renamed the library to pdfminer3 so that people can install side-by-side. This seemed like the sensible thing to do given how many forks are floating around, but I'm open to discussion.
* Similarly, I intend to rename the executables so that there are no installation conflicts with other forks of the library.

For technical comments, please open issues on https://github.com/gwk/pdfminer3. For high level community discussion about the sunsetting, I'm happy to continue the conversation here.

**Comment by jbarlow83** [comment]
@KOLANICH There's no reason to expect the euske repo to merge the fork. It's been abandoned, and some Linux distributions have moved to packaging this repo.

I do think it would be ideal if someone who was committed to regular maintenance took over as maintainer or had commit rights or was granted commit rights on this repo. I don't want to make assumptions but IIRC @ganeshtata previously said they were not necessary interested in that role long term.

**Comment by igormp** [comment]
Just updating @hugovk's answer, according to [pypi's API](https://pypistats.org/api/packages/pdfminer.six/python_major) for this year up to today.


Python | percent | downloads
-- | -- | --
3 | 87,59% | 635.744
2 | 11,75% | 85.311
null | 0,68% | 4.920
Total | 100%  | 725.975

Since Python 2 usage seems to be trending down, along with the fact that it is going into EOL next year, I see no reason to keep with the effort to support it anymore.

**Comment by pietermarsman** [comment]
I think it's best to drop Python2 support simultaneously with the Python development team, i.e. January 2020. 

It would be great if someone could already start by creating a PR that drops Python2 support.

**Comment by hugovk** [comment]
Please see PR https://github.com/pdfminer/pdfminer.six/pull/301.

**Comment by vstoykov** [comment]
The original [pdfminer (from `euske`)](https://github.com/euske/pdfminer) is now Python 3.6+. There is no Python 2 support and even no Python 3.6.

@jbarlow83 probably your statement is not correct now:
> @KOLANICH There's no reason to expect the euske repo to merge the fork. It's been abandoned, and some Linux distributions have moved to packaging this repo.
