### ISSUE TITLE
Interpreter takes very long on page with rotated text

### ISSUE THREAD

**Issue by thf24** [pdfminer/pdfminer.six#231]
Hi, thanks for the great project.

I noticed that the interpreter takes very long (5 minutes+ on my machine) to process a page when there is a lot of rotated text on it (90 degrees in the document, see attached).

this is the (shortened) code for reference:
```
fp = open(PATH_TO_FILE, 'rb')
parser = PDFParser(fp)
document = PDFDocument(parser, '')
rsrcmgr = PDFResourceManager()
laparams = LAParams()
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)
for page_index, page in enumerate(PDFPage.create_pages(document)):
     interpreter.process_page(page)
```

 
[rotated.pdf](https://github.com/pdfminer/pdfminer.six/files/2949392/rotated.pdf)

**Comment by SVasilev** [comment]
+1

**Comment by pietermarsman** [comment]
I've used the profiler to find out which lines take most time to execute. It is this ['.find()' method](https://github.com/pdfminer/pdfminer.six/blob/d6fd7e76b272e88dca67f7fabead397601ec6fce/pdfminer/layout.py#L635) in the inline 'isany()' method, in the 'group_textboxes()' method of 'LTLayoutContainer' that takes 65% of the time!

This method takes so long because the`boxes` input is a long list. And this is directly caused by `group_objects()` not grouping vertical aligned objects by default. This can be enabled by setting `LAParams.detect_vertical` to `True`.

So you can fix your problem by using `laparams = LAParams(detect_vertical=True)`.

**Comment by pietermarsman** [comment]
If @thf24 or @SVasilev agree, this issue can be closed.

**Comment by thf24** [comment]
ok thanks, I just ran some unit tests on normal (non-rotated) pages with the detect_vertical=True and didn't seem to get much a performance loss, so I wonder why this is not enabled by default? Can be closed though.

**Comment by pietermarsman** [comment]
I'm not sure either why False is the default. Maybe it deterroriates the quality of the output?

**Comment by SVasilev** [comment]
Hey there guys. Thanks for spending time on that issue. For some of my PDFs I do see slight improvement if I use `detect_vertical=True`.
But for some of the PDFs it does not look like it helps. Here is an example:
https://patentimages.storage.googleapis.com/93/e9/69/f780b3b43c6635/EP1338665A1.pdf

For this document for example page 17 takes 6.6 seconds and page 18 takes 5.71 seconds with and without the flag. Any further suggestions? Maybe I can play with other LAParams properties?

**Comment by pietermarsman** [comment]
> Can be closed though.

**Comment by SVasilev** [comment]
I don't understand why is this  issue closed. There is currently no solution to the problem.
Or you keep your bugs in separate issue tracker?

**Comment by Migliorati** [comment]
Hello, any other solutions ?

**Comment by pietermarsman** [comment]
@SVasilev @Migliorati the issue described by @thf24 is fixed by enabling detection of vertical text boxes. I consider this issue closed because this specific question is answered. 

I get that this solution does not work for all PDF's and for all code. If you have performance issues with specific PDF's or if you think pdfminer.six is slow in general for some subset of all PDF's, feel free to open a new issue.
