### ISSUE TITLE
Get two columns from PDF

### ISSUE THREAD

**Issue by robinalexandre** [pdfminer/pdfminer.six#276]
Hi there,

Firstly, thanks for this beautiful library.

I got a question for you about two columns PDFs.

When I try to get text from a two columns PDF, some text retrieved are merged between the first and the second column. I would like to know how to correct this or where is the specific code about this.

Thanks

**Comment by pietermarsman** [comment]
Hi @robinalexandre, thanks for your question. Could you attach the problematic pdf and direct us to the point where it is going wrong? Could you also give an example of the code you are using to parse the pdf?

**Comment by robinalexandre** [comment]
Hi @pietermarsman, 
Thanks for your answer.

My code is built around your parser and is not important in this case because I use what it gaves me (coordinates, text) to create a full hierarchy of the PDF.

But if you try on this file to "pdf2txt.py -o conflict.txt conflict.pdf", you will see the first problem line 26 to 28 in .txt file with "Conducteur / Quad" which are on two different columns in the PDF file. The second problem is the line 63 which should be after the line 67.

Keep me updated if you have any idea on how to resolve that and thanks again for this library

[conflict.pdf](https://github.com/pdfminer/pdfminer.six/files/3420692/conflict.pdf)
[conflict.txt](https://github.com/pdfminer/pdfminer.six/files/3420712/conflict.txt)

**Comment by pietermarsman** [comment]
The order in which the cells of the table appear in the output file is non-intuitive to me too. I'm not yet familiar with this part of the code so it will take me some time to look into.

**Comment by robinalexandre** [comment]
Any updates ?

**Comment by pietermarsman** [comment]
I've looked at this once for an hour. That helped me to understand how pdfminer is processing the pdf and converting it to text. But I still do not understand if and how the order of the objects in a pdf, or the layout of the pdf influences the output of `TextConverter()`. I am going to look at that now.

I also checked the output file with `HtmlConverter()`. The output is slightly strange but it does do a good job at outlining the table. Perhaps you could also check that (I cannot upload it due to constrains of github).

**Comment by pietermarsman** [comment]
OK, I think I understand how it works. This is my summary: 

- A pdf is basically a big hierarchical object containing pages, text, fonts, and other stuff
- This structure is parsed (page-by-page) to a Python object by `PDFPageInterpreter.render_contents()`
- At the end of each page the method `TextConverter.end_page()` is called, which calls `TextConverter.receive_layout()`. The `receive_layout()` method has all the information about the objects on a single page, where there are positioned, what fonts are used, what unicode characters to print, etc.
- Both `TextConverter` and `HtmlConvert` render the objects on the page as they receive it. The ordering in the pdf is thus the same as in the text or html output. However, the html output looks better because it uses the positioning of the pdf objects to position the `<span>` html objects.

**Comment by pietermarsman** [comment]
A possible solution could be if we change the method `receive_layout()` to reorder the objects on a page based on their vertical and horizontal positioning.

**Comment by robinalexandre** [comment]
I see more or less the same things.
Yes, I think it will be better to arrange it based on their vertical and horizontal positioning if and only if we see a gap between column_1 x1 and column_2 x0

Could you try like this something to improve it ?

Thanks for your time !

**Comment by pietermarsman** [comment]
I will try to split `TextComponent.receive_layout()` into two parts: 

- recursively getting all the text components from the `ltpage`
- sort all the text components based on there `x0` and `y0` coordinates
- "render" the text

`HtmlConverter` and `XmlConverter` also have sort of similiar `receive_layout()` methods, but I guess the order of the components is less important for them since they already use the bbox information.

**Comment by pietermarsman** [comment]
I'm digging deeper into this. As it turns out the behavior that I suggested is already implemented, and more!

The `PDFLayoutAnalyzer.end_page()` method actually orders the text objects. If `LAParams()` are given (always the case when using `pdf2txt.py`) the it `.analyze()`s all the text objects. It starts at https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/layout.py#L673. This does the following things:

- It _groups objects_. Text objects that are close together are merged. The threshold on the closeness is based on the vertical (`LAParams.line_overlap`) and horizontal (`LAParams.char_margin`) distance. Merging creates a `LTTextLineHorizontal` object that contains both text objects. This class represents a line of text and uses `LAParams.word_margin` to determine if a space should be added between the two text objects.
- It _groups text lines_. Text lines that are close together are merged. The threshold on the closeness is based on the vertical distance (`LAParams.line_margin`). Merging creates a `LTTextBoxHorizontal` object that contains these text lines. The result is called a text box.
- It _groups text boxes_. Text boxes are recursively merged. The two boxes that have the most overlap are merged first, the result is a new text box. The merging is repeated until there is only a single text box left. This creates a hierarchy of text boxes. 
- It _orders the text box hierarchy_. The order is determined by the horizontal and vertical position of the the text box. The relative importance of the these directions can be determined by `LAParams.boxes_flow`. 

Now back to your problem: it turned out that the strange output was a result of text-line-merging the "Conducteur" header with the "Termes Et Definitions" paragraph. During the text-box-merging this was merged with the "Quad" header because there is a super large overlap between the "Quad" text box and the combined "Termes Et Definitions"-and-"Conducteur" text box. 

This problem can be fixed by merging the text lines more aggressively: `pdf2txt.py conflict.pdf --line-marg 2.0 --char-margin 4.0`. This merges all the lines from a single column of the table before merging the text boxes. (The larger char margin merges all the text objects one single line in your pdf better but has nothing todo with our current problem.)

**Comment by pietermarsman** [comment]
With @robinalexandre's permission this issue can be closed now.

**Comment by robinalexandre** [comment]
Hi @pietermarsman, 

Thanks a lot for your reply.
I saw this week end exactly the same thing as you and I modify a part of the analyse function to get all the TextLines (removing the process about aggregating TextBoxes) and merging myself the TextLines based on some heuristics.

It creates a "perfect" hierarchy.

Thanks again

PS: I closed this issue now !

**Comment by probro316** [comment]
i have a pdf where the 2 columns are being merged together. I want the lines from the first column to be read first and then the second column
This is the pdf:
![Capture](https://user-images.githubusercontent.com/41687585/116791928-fe3bfe80-aad6-11eb-9e1b-10254c9da7e7.JPG)

this is the result i am getting:
![Capture2](https://user-images.githubusercontent.com/41687585/116791949-1f9cea80-aad7-11eb-97f5-72a460e34a64.JPG)

this is the code i used:

              from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
              from pdfminer.pdfpage import PDFPage
              from pdfminer.converter import XMLConverter, HTMLConverter, TextConverter
              from pdfminer.layout import LAParams
              from pdfminer.pdfdocument import PDFDocument
              from pdfminer.pdfparser import PDFParser
              import io
              import os
              
              fp = open(r'data.pdf', 'rb')
              rsrcmgr = PDFResourceManager()
              retstr = io.StringIO()
              print(type(retstr))
              codec = 'utf-8'
              laparams = LAParams(line_margin=5, char_margin=5)
              device = TextConverter(rsrcmgr, retstr, laparams=laparams)
              interpreter = PDFPageInterpreter(rsrcmgr, device)
              
              page_no = 0
              for pageNumber, page in enumerate(PDFPage.get_pages(fp)):
                  if pageNumber == page_no:
                      interpreter.process_page(page)
              
                      data = retstr.getvalue()
              
                      retstr.truncate(0)
                      retstr.seek(0)
              
                  page_no += 1
                  print(data)
                  if page_no==10:
                      break

**Comment by assa-jean** [comment]
Hello! probro316,

Currently have a project that i'm working on, and its similar as this one, please could you help on how to achieve that.
Thank

**Comment by SNMDNoor** [comment]
@probro316 Hi, I have similar type of pdf with table in the page but table is not getting extracted as expected is there a way to ignore table so that I can use it seperately
