### ISSUE TITLE
dumpdf for outline

### ISSUE THREAD

**Issue by jjhesk** [pdfminer/pdfminer.six#29]
I am confused about the dumpdf for the outline. I have read about the note and guideline but it doesnt work. https://www.binpress.com/tutorial/manipulating-pdfs-with-python/167 and it might the similar cause by #74 . Can you explain a bit more? @goulu   assume there is a block of text discovered from the miner and how can we use to bookmark command to allocation which character in the block contains such bookmark symbol?

**Comment by goulu** [comment]
Sorry about the delay @jjhesk ... Frankly I'm not a pdf guru, I can't answer ... 
If it's still a problem can you be more explicit and ask Euske maybe ?
If this old problem is not a problem anymore, you may close it. Thanks !

**Comment by pietermarsman** [comment]
Hi @jjhesk, 

If you want to know more about the document outline in pdf's, checkout the [PDF Reference Section](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf) 8.2.2 about the Document Outline: 

> A PDF document may optionally display a document outline on the screen, allowing
the user to navigate interactively from one part of the document to another.

The outline is a distinct part of the pdf that has named pointers to destinations in the pdf. The names of those pointers (called the "title) can be extracted by pdfminer, for example by using the following command on the [attached pdf](https://github.com/pdfminer/pdfminer.six/files/3728509/Chaminade2002.pdf). 

```
python tools/dumppdf.py -T chaminade2002.pdf
```

I'm considering this issue closed since it is really old, but feel free to reopen.
