### ISSUE TITLE
table extract error ?

### ISSUE THREAD

**Issue by bifeng** [pdfminer/pdfminer.six#290]
The original pdf table:
![image](https://user-images.githubusercontent.com/8215563/64936864-9a75ab00-d88a-11e9-8595-ffcc8820c4fd.png)

The extract table:
![image](https://user-images.githubusercontent.com/8215563/64936878-a7929a00-d88a-11e9-8994-eb33e38a4c97.png)

This is the command:
python pdf2txt.py example.pdf -o example.html -t html

The example pdf: http://static.cninfo.com.cn/finalpage/2019-02-01/1205830955.PDF

**Comment by pietermarsman** [comment]
Hi @bifeng, thanks for your question. You don't specify what is wrong with the output table. Obviously the layout of the numbers is wrong, but is that all? Or are there more issues that you want to address?

The wrong position of the text is because pdfminer groups the texts in the adjacent cells to aggressively. It does not take the cell dividers into account, only the vertical distance. You can change the default value (0.5) with `LAParams.line_margin`, for example by using the command line option `--line-margin`: 

```
python pdf2txt.py example.pdf -o example.html -t html --line-margin 0.3
```

Example output: 

<img width="504" alt="Schermafbeelding 2019-09-19 om 20 28 02" src="https://user-images.githubusercontent.com/3833456/65270717-04f14a00-db1c-11e9-82e7-8e4c8fc1a202.png">

**Comment by pietermarsman** [comment]
You can close the issue if this fixes your problem.
