### ISSUE TITLE
Assumptions made by PDF Miner in text positioning?

### ISSUE THREAD

**Issue by ThePrefixCyber** [pdfminer/pdfminer.six#295]
Can PDF Miner text bounding boxes be considered a deterministic result of the PDF standard? What assumptions are made about the generation, versioning, and format of the PDF? Is it possible that PDF Miner bounding box positions would be very much out of position compared to text rendered in some PDF viewing software?

**Comment by jbarlow83** [comment]
>Can PDF Miner text bounding boxes be considered a deterministic result of the PDF standard? 

It's intended to be deterministic and will be for a common subset of the PDF standard, but certainly not audited for that purpose. 

>What assumptions are made about the generation, versioning, and format of the PDF? 

The core bits about text positioning in PDF have been the same pretty much since the PDF standard was created. 

Many advanced PDF features are not supported.

>Is it possible that PDF Miner bounding box positions would be very much out of position compared to text rendered in some PDF viewing software?

Yes. In particular there are ambiguities in the PDF spec and many nonconforming files. The situation is like HTML: you have all kinds of broken files in the wild. Most sane viewers overlook problems because users expect them to, but might choose different ways of resolving problems.

**Comment by pietermarsman** [comment]
Closing this question as I consider it answered. Feel free to reopen.
