### ISSUE TITLE
pdfminer.six removes strings from .pdf file

### ISSUE THREAD

**Issue by quanticdev** [pdfminer/pdfminer.six#35]
I ran into the issue of pdfminer.six replacing strings from the text of my PDF file like 'fi', 'ff' etc. with a char which is displayed in console as a question mark (?). I guess it is some non-ASCII char since I can not replace it with searching for the actual char '?'. I found out that these strings ('fi', 'ff' and so on) are found in the file pdffont.py in a list called STANDARD_STRINGS. I tried commenting them out, to see if it would fix my problem, but it did not.

The PKG_INFO file of pdfminer.six says:
Metadata-Version: 1.1
Name: pdfminer.six
Version: 20160614
Summary: PDF parser and analyzer

If more info is needed to fix the issue, let me know. I can also provide the PDF file that produces the issue. Other than that keep the good work up, I really enjoy pdfminer.six!

**Comment by RabidCicada** [comment]
I have this issue also using pdf2txt.py...though I'm not sure goulu's fork is the place to talk about it:)

**Comment by RabidCicada** [comment]
It turns out...the pdf file itself has "I guess" been generated with those double ff''s and fi's removed or using a special "character" or command.  If I search through the original pdf manually looking for the word "staff" which appears rendered.  Adobe itself doesn't find it.  So the characters are actually not two f's back to back.  I find the same thing for the fi's...the original pdf itself doesn't have the word "find" it has some wierd 'fi' combo character I guess then 'n' and 'd'.

So I'd suggest looking to see if your original pdf has "wierd" characters instead of what you see with your eyes.

**Comment by RabidCicada** [comment]
http://www.fileformat.info/info/unicode/char/fb00/index.htm
https://en.wikipedia.org/wiki/Typographic_ligature

**Comment by goulu** [comment]
Is it:
1. a unicode problem, i.e the corresponding unicode char is not produced. 
2. or is it a text problem, i.e you expect such characters to be translated to "ff" or "fi" ascii strings ?
In the first case it's a bug and we need a test case with expected result
In the second case it's an enhancement ...

**Comment by RabidCicada** [comment]
Here's my code and the pdf to reproduce.
As an aside.  Perhaps I need to be educated on Unicode.  Maybe I simply don't know how to deal with unicode.  The output file looks like normal ascii except for the messed up ff fi and a page divide character from the pdf.

If I try to use StringIO I get a decode problem on getvalue() because the stream seems like it tried to mix unicode and ascii.  Can you tell me if I'm doing something wrong or if the miner/streams are doing something wrong?

#!/usr/bin/env python
import sys
from pdfminer.pdfdocument import PDFDocument, PDFXRef
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfdevice import PDFDevice, TagExtractor
from pdfminer.pdfpage import PDFPage
from pdfminer.converter import XMLConverter, HTMLConverter, TextConverter
from pdfminer.cmapdb import CMapDB
from pdfminer.layout import LAParams
from pdfminer.image import ImageWriter
from io import BytesIO

def extract_pdf_text(fp):
    debug=0
    PDFDocument.debug = debug
    PDFParser.debug = debug
    CMapDB.debug = debug
    PDFPageInterpreter.debug = debug
    PDFXRef.debug = debug
    codec = 'utf-8'
    laparams = LAParams()
    rsrcmgr = PDFResourceManager(caching=False)
    outfp = BytesIO()#Supposedly inefficient...but if I use StringIO I get decoding errors during getvalue()
    device = TextConverter(rsrcmgr, outfp, codec=codec, laparams=laparams)
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.get_pages(fp, set(),check_extractable=True):
        interpreter.process_page(page)
    device.close()
    output = outfp.getvalue()
    outfp.close()
    return output
[resume.pdf](https://github.com/pdfminer/pdfminer.six/files/719998/resume.pdf)

**Comment by RabidCicada** [comment]
Shout out to @eteran for his resume:).  And for doing awesome work on edb

**Comment by shreeniwas-sapre** [comment]
Ligatures (ff, fi, fl etc) could get into the pdf through the typesetting software. 

http://tex.stackexchange.com/questions/33476/why-cant-fi-be-separated-when-being-copied-from-a-compiled-pdf.

So in such cases, whether the ff can be separated may depend upon the software used to prepare the pdf.

**Comment by RabidCicada** [comment]
Ultimate fate declaration.  There is nothing pdfminer.six can do about this.  I spent a lot of time tracking down the problem.  The problem demonstrated in my sample resume pdf provided above is:
The PDF itself provides partial font resources.  Those PDFCIDFont's (Using pdfminer's terminology) provide ToUnicode helper resources (in the pdf itself).  Those ToUnicode resources explicitly and incorrectly map the CID's for 'ff' ligature and 'fi' ligature to '\x00' unicode mappings.

Without ToUnicode mappings provided in the pdfresources you effectively have to OCR the text from rendered output (which is clearly beyond the scope of pdfminer).

The problem in my case is not with pdfminer....it's 100% on the tool that made the pdf and incorrectly mapped the CID's to incorrect unicode values...then "helpfully" provided them in the pdf font resource as the ToUnicode Map.

*Sigh*

**Comment by RabidCicada** [comment]
I think this is good to close...it's a problem with the pdf creator itself and not pdfminer

**Comment by quanticdev** [comment]
Thanks everyone for the insights on this problem anyway! Solutions seem to be either OCR or letter matching with a big word list. Anyway both are probably out of the scope of this project.

**Comment by quanticdev** [comment]
Might be relevant for anyone interested to overcoming this issue: https://elifesciences.org/labs/5b56aff6/sciencebeam-using-computer-vision-to-extract-pdf-data
