### ISSUE TITLE
pdf2txt.py -t xml not extracting all information for extended encoding?

### ISSUE THREAD

**Issue by pbienst** [pdfminer/pdfminer.six#358]
I'm trying to get the text out this mixed Arabic-English document: 

https://www.dropbox.com/s/rfoisx2bw651l08/a.pdf?dl=0

A command like 'pdf2txt.py -t xml -p 22 a.pdf' gets all the English text information.

For the Arabic text, it seems it uses different embedded fonts/font-size combinations to render it, but I don't think I get all the information I need to reconstruct the Arabic. The number of characters seems roughly OK, but there simply is not enough variety in the values, as many of them map to colons or periods.

This suggests to me that there's some non-ascii encoding going on, and that pdf2txt somehow truncates to the most significant bits.

Could this be the case? If so, how could I get all the raw info out of the pdf, so that I can continue analysing it and mapping the characters to the correct unicode?

**Comment by pietermarsman** [comment]
Do you know the origin of this pdf document? It looks like it is a scanned book with optical character recognition (OCR) applied to it. The OCR software probably only recognized the Latin alphabet correctly, and not the Arabic characters. 

A couple of observations that support this: 

- The cover of the book is a noisy picture. Other images of the cover are sharp. There is also a tiny white line at the top of the first page, because the book was slightly missaligned in the scanner. 
- If you zoom in onto the characters you can see noise around all characters. 
- There are some traces of use, e.g. on the third page there is a stain. That's probably not in the digital edition. ;)
- If you copy the text you get characters that are almost always correct for the English text, but not always. If you copy "Thematic vocabulary list | vi" on the sixth page, you get an `I` (capital i) instead of an `|` (pipe character).

Why is this important? Pdfminer.six extract the text from pdf using the "source code"  of the pdf. It does not  use OCR of any sort. This is a scanned document; basically images with some OCR information on top of it. You see the scanned document, but if you extract the text (e.g. by copying, or by using pdfminer.six) you get the result from the OCR.

If you want to extract the Arabic text you should probably use an OCR tool that does understand Arabic.

**Comment by pbienst** [comment]
Makes sense, thanks for the detailed explanation!
