### ISSUE TITLE
Add documentation for high-level function extract_pages()

### ISSUE THREAD

**Issue by pietermarsman** [pdfminer/pdfminer.six#361]
I've just added this function to get easy access to the `PDFPage` objects but it is not yet in the readthedocs documentation. It should be added there with some tutorials.

**Comment by jstockwin** [comment]
@pietermarsman happy to help out with this if you like?

For reference, the commit you mention is here: https://github.com/pdfminer/pdfminer.six/commit/fff3ac2ba6121660e0f7178150d665215d8586d7

Where in the docs would you like this?

Could I also suggest an enhancement that allows you to pass a file-like object to this, so I can e.g. do this from a IO stream instead of having to have the PDF on my hard drive?

**Comment by pietermarsman** [comment]
> Where in the docs would you like this?

I try to follow [this](https://www.divio.com/blog/documentation/) structure of the documentation (still in early fases though). It is already added to the API reference. I think it is most useful to add a section to the tutorials section. For example, how to use `extract_pages` to [extract the fontsize](https://github.com/pdfminer/pdfminer.six/issues/202) of every character, or a [set of font names](https://github.com/pdfminer/pdfminer.six/issues/380), or maybe a list of figures. 

> Could I also suggest an enhancement that allows you to pass a file-like object to this, so I can e.g. do this from a IO stream instead of having to have the PDF on my hard drive?

Great idea! This is also applicable to the other `high_level` functions. Could you create an issue for this?

**Comment by jstockwin** [comment]
> Great idea! This is also applicable to the other high_level functions. Could you create an issue for this?

Just for anyone wanting to follow the trail, I created #392

**Comment by jstockwin** [comment]
A tutorial makes sense - I'll have a look at getting this done when I have time. Feel free to assign me to this
