### ISSUE TITLE
Allow negative line margin

### ISSUE THREAD

**Issue by jstockwin** [pdfminer/pdfminer.six#383]
**Is your feature request related to a problem? Please describe.**

[Example PDF File](https://www.dropbox.com/s/jjhlbsynrnjuq6i/negative_line_margin_example.pdf?dl=0)

In some of the PDFs I deal with, it is possible that the bounding boxes of different lines of text overlap, but I do not want them grouped into one text box. For example, all the text in the example pdf liked above (example code at the bottom) gets grouped into one text box, no matter how small the line margin.

The `line_margin` layout parameter is used to determine how close lines need to be for them to be grouped, but in my case (because they overlap) it is impossible to set it small enough that they don't get grouped.

I appreciate that a `\n` character is added when lines are merged, but I require the structure of your text box elements for my project.

**Describe the solution you'd like**
Being able to set a negative `line_margin`, meaning "two lines of text must overlap by at least this value for them to be grouped into one text box" would solve this issue.

In terms of code, we'd adapt [find_neighbors](https://github.com/pdfminer/pdfminer.six/blob/develop/pdfminer/layout.py#L418) to work with a negative `ratio` parameter. I believe the `objs = plane.find(...)` would already work as intended, but we then do other checks of the form `abs(...) < d` which will always be false due to `d` being negative.

I'd be happy to work on a fix, but might need a few pointers about how to adapt these checks for a negative `ratio`. For me, it's not really obvious why we're checking the `height` and `x`-position of the elements based on something related to `line_margin` and `height`... (these checks are also discussed in the additional notes of #382, for a related reason)

**Describe alternatives you've considered**
An alternative would just be to have an option to disable the merging of lines entirely, e.g. you can set `line_margin` to 0 to disable the behaviour. We'd still need to edit to checks as `abs(..)<0` is always `False`, but perhaps `abs(...) <= 0` is acceptable in that case.

**Example code**
```
from pdfminer import converter, pdfdocument, pdfinterp, pdfpage, pdfparser
from pdfminer.layout import LTTextContainer, LAParams
path_to_file = "centered_text_example.pdf"

_LA_PARAMS = LAParams(line_margin=0.00000001)

with open(path_to_file, "rb") as pdf_file:
    parser = pdfparser.PDFParser(pdf_file)
    document = pdfdocument.PDFDocument(parser)
    resource_manager = pdfinterp.PDFResourceManager()
    device = converter.PDFPageAggregator(resource_manager, laparams=_LA_PARAMS)
    interpreter = pdfinterp.PDFPageInterpreter(resource_manager, device)
    for page in pdfpage.PDFPage.create_pages(document):
        interpreter.process_page(page)
        results = device.get_result()
        elements = [
            element for element in results if isinstance(element, LTTextContainer)
        ]
device.close()

print(elements)
```

**Comment by pietermarsman** [comment]
A summary for myself: 

- Currently we allow a positive `line_margin` parameter that specifies the maximum distance between two lines. The distance is measured between the bottom of one line, and the top of the other line. This distance should be smaller than `line_margin * height` where `height` is the height of the bounding box of one of the two lines (arbitrary). 
- If lines overlap, i.e. the distance is 0, then there is no way of preventing these lines to be merged in a `LTTextBox`. 
- We could add this feature by giving special meaning to negative `line_margin` values.
- Another option is to add parameters for enabling/disabling specific parts of the layout analysis.

Enabling/disabling specific parts of the layout analysis is an interesting idea. It should be incremental, i.e. by disabling `group_textlines()` you are also disabling `group_textboxes()`. Currently, we only allow to explicitly enable/disable everything. By adding the negative parameter values, we also allow to disable a specific part of the layout analysis. E.g. by setting `line_margin` to -10000, non of the lines will be merged into a text box. I prefer this approach over adding explicit parameters for disabling specific parts of the layout proces, because the "negative parameter" approach is more granular. Optionally, we could add a special value `DISABLE=-math.inf`. 

> For me, it's not really obvious why we're checking the height and x-position of the elements based on something related to line_margin and height... (these checks are also discussed in the additional notes of #382, for a related reason)

This was introduced in f638784e1d9e35cbb47cb09c039f7226080728e9 as experiment layout features. It has been there for ages. It makes sense to require lines to have a aligned side (either left or right). But I agree that using the `ratio * height` as a threshold is weird, and undocumented. Perhaps we could change it to `height`?

> I believe the `objs = plane.find(...)` would already work as intended

Yes, I think so too. 

> but we then do other checks of the form `abs(...) < d` which will always be false due to d being negative.

Letting `d = self.height` solves this. I think that this is at least applicable for the x-axis. 

The `abs(obj.height-self.height) ` is more difficult. The height of a `LTTextLine` is determined by all the characters in it. There height is determined by the font. I think that, in most cases, the height of lines in the same paragraph is the same. But I would not be surprised if a lot of PDF's have small differences in heights of lines in the same paragraph. Some tolerance is needed. Maybe compare the rounded heights? Or use `abs() < max(0, d)`? Or add a new parameter?

**Comment by jstockwin** [comment]
It sounds like you're leaning towards allowing negative values to me. I'll wait for #384 to be sorted before I start changing this, as the two fixes are going to touch the same lines.

I'm trying to work out what line_margin values of less than `-1` mean. Since the lines in question are the same height (within a tolerance), if we're considering the case where `d = -1 * height` then actually this means the two lines are completely on top of each other.

In some way, this feels like it should be the minimal case, as if the second line is above the first then they should be considered the other way round.

Looking at the code, 
```
d = ratio*self.height
objs = plane.find((self.x0, self.y0-d, self.x1, self.y1+d))
```
I would actually say that perhaps `line_margin = - 0.5` is the minimal case - this means the bounding box being passed to `plane.find` is actually a line. Any smaller than this and the `y1` is going to be bigger than the `y0`, which isn't a valid bounding box at all.

That said, it does feel like we should be able to handle all the way down to `-1` somehow. What if lines overlap by 75% of their height? We should be able to merge lines that overlap by 80% but not ones that overlap by 70%, if we like.

Perhaps I just need to try it and test it, but it feels as though it needs a bit of thought. I guess maybe the `plane.find` needs a `max(d, 0)` in there so we get all of the text boxes that touch the one in question, but then we need to do some extra filtering after this...

**Comment by pietermarsman** [comment]
> It sounds like you're leaning towards allowing negative values to me.

Indeed

> I'll wait for #384 to be sorted before I start changing this, as the two fixes are going to touch the same lines.

Good plan

About the minimal case, there are a couple of options:

1. Use -0.5 as minimal
2. Use -1.0 as minimal and use `objs = plane.find((self.x0, self.y0-max(d, 0), self.x1, self.y1+d))` such that the y-start of the bounding box is not below `y0`.
3. Likewise, use -1.0 but divide it by 2 if it is negative

All of these are a bit akward. I think it is because the `plane.find()` method does not measure overlap but if the other line is somewhere in the bounding box. I think option 1. or 3. is the best we can do because they are symmetric.

**Comment by jstockwin** [comment]
@pietermarsman So I think I'll try to allow negative values, and add a minimum of `-0.5` when using `plane.find` (i.e. option 1 above).

We still need to decide how we're handling the tolerance in the height, and in the x-axis for the alignment. Note we've added private methods for this now (https://github.com/pdfminer/pdfminer.six/pull/384/commits/a55d4141bf80509ea0a76165f39d1368d3685d85) so hopefully the code will at least be clear.

I'm actually wondering whether `d = self.height * abs(ratio)` (where `ratio = la_params.line_overlap` works). In some sense then the `line_overlap` is something to do with how "messy" the PDF is? The only issue is if you pass `line_overlap=0` you end up needing the height and x-alignment to be perfect which doesn't seem ideal...

Another thought is that perhaps this should be another parameter, but then I'd be unsure exactly what to call it, and in exactly how many places it should be used. Perhaps something like `alignment_tolerance`? But it should be noted that we'll probably use it for both alignment and checking if the heights are similar enough...

Any more thoughts?

**Comment by jstockwin** [comment]
Hmm, actually @pietermarsman I've just started to have a look at this, and suddenly my example doesn't reproduce the issue any more..

I've run `git bisect` and found that this commit https://github.com/pdfminer/pdfminer.six/commit/fff3ac2ba6121660e0f7178150d665215d8586d7 is where my example stops reproducing the issue.

See the below screenshot:
![image](https://user-images.githubusercontent.com/8227759/77905885-ed3f0f00-727e-11ea-8cc4-90e38dba5a1b.png)

- Before that commit, the highlighted (orange) was taken to be the bounding box of the text, and therefore you can see that there is an overlap.
- After that commit, it looks like we start using the actual bounding box of the characters, and so they no longer overlap.

As such, the initial reason for me submitting this issue is likely resolved. However:
- It's perhaps still relevant, but only if the actual text did overlap (which would be a little strange?).
- Perhaps there's a discussion to be had around `d = self.height * ratio` and potentially adding a new parameter.

That said, I'm also happy for the issue to be closed...

What do you think?

**Comment by pietermarsman** [comment]
I'm glad that fff3ac2 fixes the issue for you. 

This also makes it more clear what the problem was: having logic on bounding boxes that do not represent what we care about. Previously, when the bounding box could be bigger than the actual character, we would like to specify a minimum overlap. Currently, when the bounding box represents the character better, I don't see a point in doing that anymore. Because it will almost never happen that someone wants to prevent lines being merged when they overlap. 

I'm closing this, as we both agree that the initial point is not relevant anymore. 

Thanks for all your research on this! 

Lets create a new issue for the discussion about `d = self.height * ratio`.
