### ISSUE TITLE
Iconsistent layout, misbehaving file(maybe unicode related?)

### ISSUE THREAD

**Issue by Filip98** [pdfminer/pdfminer.six#390]
I'm extracting this file:
[file](https://nissrednjastrucna.edu.rs/data/documents/Opsti-deo.pdf)
Which is in a consistent format

And minus a lot of newlines half of the produced text is as it should be
`
A) line
B) line
C) line
`
But I get a lot of this:
`
A)
B)
C)
line
line
line
`
or this
`
line
line
line
A)
B)
C)
`
or even better, one or several lines being in and the others out

Ive compared it to the first "questions" pdf I found on google and it performed well
[file2](https://www.hws.edu/academics/career/pdfs/intvq.pdf)

**Comment by jstockwin** [comment]
It's grouping things as follows:

![image](https://user-images.githubusercontent.com/8227759/76847243-ab9f7480-6839-11ea-8b61-5d995fc27d85.png)

I think from the above question 1 and 2 work fine, but question 3 has an issue?

My suspicion is that the ones with smaller answers are (or perhaps smallest first word in all the answers) are getting split into two boxes because the words don't get merged into the same line. This should be what `word_margin` of `LAParams` controls, but I've just tried setting it really big and it still won't merge them into one box. I've also tried changing `line_margin` to be smaller so that the lines for A B and C are separate. This didn't help much...

I do think it should be possible to get this to merge properly, but needs a bit of debugging. (Also I could just be completely wrong)

**Comment by Filip98** [comment]
You're right, question 3 is read wrong, but e.g question 11 ends up like:
```
11.  Мајбах је конструисао: 
батеријско  паљење; 
карбуратор; 

а) 
б) 
в)  пумпу високог притиска.
```
But I don't get what do you mean smaller
![ifhwifa](https://user-images.githubusercontent.com/4060824/76883116-f04bff80-687b-11ea-9e12-80d45a4a17f2.jpg)
I can't spot the difference between б and в

3, 11, 24, 33 show all the types of "mutations"
I was suspecting unicode because 76-:-93 is the English section in srp_latin encoding(ascii+modifications like ć, ž, č) and the results are drastically better with only 78, 81 being odd
I could be wrong tho

It might be worth noting that textract method="tesseract"(which uses pdftoppm) gets the answers better but messes up the questions
p.s Any way to fish out the correct answer? ¯\_(ツ)_/¯

**Comment by jstockwin** [comment]
In 11 it detects two text boxes, one with the question and the top two answers, and the other with just the letters and the bottom answer.

![image](https://user-images.githubusercontent.com/8227759/76948041-6d1fbd80-68fe-11ea-9b0d-5ab788d964b4.png)

It could be unicode related, I don't know. I'll try to have a dig into the merging logic to see why it doesn't correctly merge all this into a single text box...

**Comment by jstockwin** [comment]
Okay, so I think it's as simple as this: Sometimes the distance between the letter (i.e. `a)`) and the answer is a little bit larger, and so they don't get merged into a single line, and therefore never get merged into a single text box. I don't think it's anything to do with unicode.

I thought that making the word margin larger would fix this, but it didn't. The reason behind this is it's actually the character margin that we need to increase.

@Filip98 If you run your code with `LAParams(char_margin=3)` I think it will work much better. Please try it and let me know.

From looking at the code, I can see that the `word_margin` is only considered when we've already decided to merge to characters into a single line. If you look at the defaults `char_margin=2` and `word_margin=0.1`, this becomes a bit more obvious.

The documentation reads (at least to me) as though "anything with distance less than char_margin will be grouped into a word" and then after that "any words with distance less than word_margin" will be grouped into a line.

In actual fact, the logic is "any two characters closer than char_margin will be grouped into a line. During this grouping, if they are further apart that word_margin then a space will be inserted". At no point is there actually a concept of "words" that get grouped.

The logic itself is fine, but I think the documentation should be made a bit clearer, perhaps. If your words not getting grouped into a line because they are too far apart, it's likely you actually need to increase "char_margin" and not "word_margin". The only reason to increase "word_margin" would be if two words are getting pushed together without a space in between them.

**Comment by Filip98** [comment]
You're absolutely right, I did
`pdf2txt.py -M 3 Opsti-deo.pdf`
And the only ones that came out wrong are 68 a), 78, 81
running
`pdf2txt.py -M 3.1 Opsti-deo.pdf`
Ends up with only 68 a) being wrong, but it has some extra space, -M 4.1 is enough to pick it up too
I suppose there's a reason why the char margin is 2 by default but it might not be bad to reconsider or attempt to detect this

I just noticed that regardless..
New lines get read as double new lines

**Comment by pietermarsman** [comment]
> The documentation reads (at least to me) as though "anything with distance less than char_margin will be grouped into a word" and then after that "any words with distance less than word_margin" will be grouped into a line.
> 
> In actual fact, the logic is "any two characters closer than char_margin will be grouped into a line. During this grouping, if they are further apart that word_margin then a space will be inserted". At no point is there actually a concept of "words" that get grouped.
> 
> The logic itself is fine, but I think the documentation should be made a bit clearer, perhaps. 

I totally agree! 

Let's close this issue when the documentation is updated. 

When updating the documentation, make sure to also update: 
- pdfminer/layout.py
- tools/pdf2txt.py
- tools/pdfdiff.py
- docs/source/topics/converting_pdf_to_text.rst
