### ISSUE TITLE
Chunk by words or lines in XML

### ISSUE THREAD

**Issue by spolpen** [pdfminer/pdfminer.six#40]
I'm trying to extract all the text from a PDF by this version of PDFminer, but it chunks by letters although I change the -M, -L or -W options.

I need to extract it in XML format, ¿is there any option to extract word by word or line by line?

Thanks

**Comment by Daniel-KM** [comment]
I made the pull requests https://github.com/euske/pdfminer/pull/137 and https://github.com/euske/pdfminer/pull/138 to add an option for that. This is on the euske release, but I can upgrade it here if it will be merged.

**Comment by goulu** [comment]
Hi Daniel,
yes if you PR here and it passes the tests, then it will be merged.
Thank you !

**Comment by pietermarsman** [comment]
Hi @spolpen,

The XML output indeed outputs a tag for each character using the `text` tag. There is no specific way that words are encoding in this format. This is because there is no specific concept related to words in pdf's. It is just characters seperated by spaces. 

Pdfminer does however provide information about lines (with the `textline` tag in the XML output) and groups of lines (with the `textbox` tag in the XML output). This grouping of characters is a result of the parameters `LAParams` you already mentioned, e.g. `word-margin`, `char-margin`, etc. 

I'm considering this issue as closed since it is really old, feel free to reopen.
