### ISSUE TITLE
pdf2txt.py and pdfdump.py should have a shebang

### ISSUE THREAD

**Issue by fabbox** [pdfminer/pdfminer.six#405]
Both scripts in tools/ doesn't contain python interpreter line (#!/usr/bin/env python) which prevent their correct execution when packaged and installed. 

From https://bugs.archlinux.org/task/65939 : 

#!/usr/bin/env python was removed from pdf2txt.py by [1] [2] and from duppdf.py by [3] [4].
The commit messages do not explain the removal while commit [5] notes the need for them.

[1] https://github.com/pdfminer/pdfminer.six/commit/bc034c8e59d90e9b2cb8697a1d2fe9a33401761e
[2] https://github.com/pdfminer/pdfminer.six/pull/329/commits/d93a73f87b65837bcbec8ab1b1edc43d681fbc9f
[3] https://github.com/pdfminer/pdfminer.six/commit/6cc78ee1249558fa3a5e0cc8f296ed736460905d
[4] https://github.com/pdfminer/pdfminer.six/pull/321/commits/7aa180d2310f5c87c28ad9cf0f35494c308fe079
[5] https://github.com/pdfminer/pdfminer.six/commit/0fdebc6739143e716a4cb8b7f26ecf012e314cfc

**Comment by pietermarsman** [comment]
I think I removed some in the past because I did not understood what they are for. Adding them adds another way of interacting with pdfminer.six; using `$ pdf2txt.py file.pdf` (without prefixing it with python). 

I think its a good thing if we introduce them again. Are there shebangs that work for all kinds of python environments (e.g. conda, virtualenv, pipenv, system python, etc.)?

Also see #217

**Comment by fabbox** [comment]
Yes, it should work with most of python environments even if I'm not sure on the compatibility with Windows. Note that additionnaly I didn't get the opportunity to test with conda.

**Comment by pietermarsman** [comment]
According to the python [docs](https://docs.python.org/3/using/windows.html#shebang-lines) it is also compatible with windows.

**Comment by eli-schwartz** [comment]
> I think I removed some in the past because I did not understood what they are for.

They define how to run a program on Unix. Since they are installed as command-line executables in https://github.com/pdfminer/pdfminer.six/blob/d79bcb75ea08442df0c69af050c0070d0ae036b4/setup.py#L31-L34
there is no choice: they *must* have those shebangs, and to do otherwise is utterly broken. For compatibility with ancient Unix systems, there is a fallback to try (and fail) to execute them as shell scripts.

> Are there shebangs that work for all kinds of python environments (e.g. conda, virtualenv, pipenv, system python, etc.)?

`#!/usr/bin/env python` will locate the currently active python, whether that is a venv or the system python.
