### ISSUE TITLE
A question of expectations: The output is very approximate, and the HTML could be better

### ISSUE THREAD

**Issue by SailingSteve** [pdfminer/pdfminer.six#409]
I am trying to highlight political endorsements for use in the non-partisan [WeVote.us](wevote.us) project.  The output from pdfminer.six looks rough, and in places is not very good HTML, which makes it hard to programmatically find the names of the candidates.  My implementation is an unmodified installation of pdfminer.six, except that I copied the [pdf2txt.py](https://github.com/wevote/WeVoteServer/blob/develop/pdfminer_six/pdf2txt.py) into [my Python project](https://github.com/wevote/WeVoteServer) and call it's main from another class.

This is not a complaint -- It is almost a yes/no question -- Is this what I should expect from pdfminer.six, or are there settings that I could change, or libararies that I could update to improve  the output?

Here is an example of an input pdf: https://www.iuoe399.org/media/filer_public/45/77/457700c9-dd70-4cfc-be49-a81cb3fba0a6/2020_lu399_primary_endorsement.pdf

<img width="739" alt="Screen Shot 2020-03-30 at 8 53 28 AM" src="https://user-images.githubusercontent.com/6923653/77933790-0b4b4600-7264-11ea-8979-5dc55884b2ef.png">

Here is the output:  https://wevote-temporary.s3.amazonaws.com/tmpx0akshhw.html

<img width="656" alt="Screen Shot 2020-03-30 at 8 55 31 AM" src="https://user-images.githubusercontent.com/6923653/77933938-3fbf0200-7264-11ea-9cc6-eb1c61c56f50.png">

The problem where columns are too thin and text is wrapping, is far less important than the issue where in some areas, the names are made into columns with HTML breaks instead of divs or spans or table formatting:
```
<span style="font-family: Helvetica; font-size:9px">Aaron Ortiz (D)*
  <br>Theresa Mah (D)
  <br>Nidia Carranza (D)*
  <br>Delia Ramirez (D)
  <br>Lamont Robinson (D)
  <br>Sonya Harper (D)
  <br>Emanuel “Chris” Welch (D)
  <br>La Shawn Ford (D)
  <br>Lakesia Collins (D)*
  <br>Omar Williams (D)*
```
 Is this the best that can be done with pdfminer.six, or are there ways to improve it?

**Comment by pietermarsman** [comment]
Hi @SailingSteve, 

The output you are seeing is currently the best output pdfminer.six can provide. 

There are a couple of issues that are not yet fixed:

- The displayed fonts are not the ones that are specified in the PDF. If the browser does not know Helvetica (mine doesn't) it renders a different default font. This font has different sizing and messes up the output. I've seen this before and now created issue #410 for it. 
- Another thing is that the generated bounding box could be really tight. If you reduce the font-size to 8.9 (instead of 9) it might fit in there. Maybe we should increase the bounding boxes by 1 pixel in every direction to fix this.

**Comment by SailingSteve** [comment]
Thanks @pietermarsman  -- your reply answers my question.  This is still a great tool, with some issues to resolve.

**Comment by jstockwin** [comment]
Due to the "your reply answers my question", I am closing this issue. It looks as though there is another issue for things that need changing.

feel free to comment/re-open if you disagree.
