### ISSUE TITLE
"fi" not recognized

### ISSUE THREAD

**Issue by mengcius** [pdfminer/pdfminer.six#426]
"fi" The two letters are not recognized when they are joined together, to "??".

pdf eg. https://arxiv.org/pdf/1503.03832.pdf

**Comment by pietermarsman** [comment]
It is actually extracted as the [Latin Small Ligature Fi ](https://www.compart.com/en/unicode/U+FB01). Perhaps your terminal/text-editor does not support unicode and that's why it shows "??", but on my terminal it shows "ﬁ" (single character). 

This is caused by the to-unicode mapping in the pdf and cannot be fixed (or mapped) by pdfminer.six. 

You can replace the character for this specific pdf if you really need to:

```shell
tools/pdf2text.py 1503.03832.pdf | sed -e 's/ﬁ/fi/g'
```
