### ISSUE TITLE
How to extract font size with words ? 

### ISSUE THREAD

**Issue by tuner007** [pdfminer/pdfminer.six#452]
i can check that pdfminer provides output in form of text,html,xml and tag.

In text file output it is difficult to differentiate headings with next sentences.
I thought if i can get font size for words i can use it.

I tried XML but font size is available for each and every letter instead of a word.

Is there a simple way out to separate headings with next sentences?

Thanks !

**Comment by pietermarsman** [comment]
Hi @tuner007,

There is no way for pdfminer.six to get the font-size of words, since for each word the font-sizes of each of the letters can differ.

You can create your own logic on top of the output of pdfminer.six by programatically extracting the text. For example, to get all the characters with their font sizes you can do the following: 

(Note I am using the font-size-test.pdf from the samples directory in the pdfminer.six repository. But you can use any pdf you want)

```
from pdfminer.high_level import extract_pages
from pdfminer.layout import LTTextBox, LTChar


path = '/home/pieter/projects/pdfminer-upstream/samples/font-size-test.pdf'
for page in extract_pages(path):
    for text_box in page:
        if isinstance(text_box, LTTextBox):
            for line in text_box:
                for char in line:
                    if isinstance(char, LTChar):
                        font_size = int(round(char.size))
                        heading = 'is heading' if font_size > 16 else ''
                        print(char.get_text(), '-', font_size, heading)
```

The start of the output is: 

```
O - 28 is heading
S - 28 is heading
X - 28 is heading
  - 28 is heading
S - 28 is heading
t - 28 is heading
y - 28 is heading
l - 28 is heading
e - 28 is heading
s - 28 is heading
  - 28 is heading
1 - 12 
2 - 12 
  - 12 
1 - 12 
2 - 12 
  - 12 
1 - 16 
6 - 16 
  - 16 
```

An example for extrac
