### ISSUE TITLE
Text recognized as one big box

### ISSUE THREAD

**Issue by Borstix** [pdfminer/pdfminer.six#487]
I am detecting anchor words to automatically place the signature of the user at the correct position.

```
    fp = open(filename, 'rb')
    rsrcmgr = PDFResourceManager()
    laparams = LAParams()
    device = PDFPageAggregator(rsrcmgr, laparams=laparams)
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    pages = PDFPage.get_pages(fp)
    pagecounter = 1
    for page in pages:
        interpreter.process_page(page)
        layout = device.get_result()
        for lobj in layout:
            if isinstance(lobj, LTTextBox):
                x, y, text = lobj.bbox[0], lobj.bbox[3], lobj.get_text()
                if "Mit freundlichen Grüßen" in text:
                    return pagecounter, x, y
```
Most pdf files work this way. On some files, complete parts of the document body are recognized as one text box so I am not getting the position of the anchor word ("Greetings") but the position of the "Box" which begins e.g. 20 lines above.

A document with this error is here: [https://nx.borstinet.de/index.php/s/Eb8FdLDZ2SNRJbm](https://nx.borstinet.de/index.php/s/Eb8FdLDZ2SNRJbm)
Any ideas? Thanks!

**Comment by jstockwin** [comment]
Hey @Borstix,

You need to adjust your Layout Parameters. See https://pdfminersix.readthedocs.io/en/latest/reference/composable.html#laparams and https://pdfminersix.readthedocs.io/en/latest/topic/converting_pdf_to_text.html.

In your case, you can reduce the `line_margin` which is what controls how close two lines need to be before they are grouped.

If you change `laparams = LAParams()` to `laparams = LAParams(line_margin=0.0001)` it should work.

I would note that your example PDF seems to have a lot of blank spaces inserted, which is why the box is so big. See the below screenshot (in which I have reduced the line margin):
![image](https://user-images.githubusercontent.com/8227759/92391910-5cb20800-f115-11ea-8ce0-f25bc5ac6a16.png)

**Comment by Borstix** [comment]
Hi @jstockwin ,
Wow, I did not expect this prompt reaction time, thank you very much! Your fix is working very well!

Greetings
Sebastian
