### ISSUE TITLE
open_filename doesn't accept a pathlib object

### ISSUE THREAD

**Issue by estshorter** [pdfminer/pdfminer.six#491]
**Bug report**

If the `filename` argument is a `pathlib` object, it is mistakenly recognized as a file handler.
I think `open_filename` should accept a `pathlib` object.
https://github.com/pdfminer/pdfminer.six/blob/0b44f7771462363528c109f263276eb254c4fcd0/pdfminer/utils.py#L14-L25

**Comment by pietermarsman** [comment]
Hi @estshorter,

I was hesitant at first, because there might be a lot of other packages that also do some kind of path representation. And they probably all can map it to a string (which we already support). But since pathlib is a python core package we can support it. 

When changing this, it should also be more verbose in case of any expected input. So maybe use `isinstance(something, io.IOBase)` for the file like output, and add one for the pathlib, and if none match raise an error.
