### ISSUE TITLE
pdf2txt.py cannot be found in windows anaconda environment

### ISSUE THREAD

**Issue by sagniknitr** [pdfminer/pdfminer.six#508]
- A description of the bug

  once you install pdfminer.six in anaconda, you cannot run pdf2txt.py 

- Steps to reproduce the bug. Try to minimize the number of steps needed. 

1) Start anaconda in windows
2) pip3 install pdfminer.six
3) pdf2txt.py samples/simple1.pdf

**Comment by pietermarsman** [comment]
The pdf2txt.py script is added to a bin/ or scripts/ directory somewhere on your system. I'm using linux and virtualenvs so I can't really help you, but in my case the script is added tot the bin/ directory of my virtualenv. And this directory is also on my system path (because virtualenv does that). 

You can use [this](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-path/#windows) to find where the anaconda python is installed, and then look around it the bin/ and/or scripts/ directory in that dir. If you find it you need to add its directory to the environmental path.

**Comment by idler921** [comment]
It is in C:\Users\username\Anaconda3\Scripts\
