### ISSUE TITLE
LTWord

### ISSUE THREAD

**Issue by NikZak** [pdfminer/pdfminer.six#519]
It would be nice to have the LTLine object split into LTWord objects and then into LTChar rather than directly into LTChar

Like this
{LTTextBox: [{LTTextLine: [{LTWord: [{LTChar: ...}]}, ... ]}, ...]}

Why? word_margin is analyzed but the result of this analysis is not saved in a separate object - only LTAnno() is added

LTWord may represent a part of a word when a part of the word is carried over to the next line

**Comment by pietermarsman** [comment]
Hi @NikZak, thanks for the suggestion. I like the idea of having an output representation that represents/describes the steps of the layout algorithm better. 

However, this will break a lot of peoples code, and that's why I'm hesitant to accept the suggestion. Also, if you need this output, pdfminer.six allows to implement your own `PDFDevice` and output it like you described. For these reasons I'm going to close this issue.

Let me know if  you have thought of a miracle solution to prevent breaking changes, and we will reopen this issue :)
