### ISSUE TITLE
Organization icon and members, spelling

### ISSUE THREAD

**Issue by bittner** [pdfminer/pdfminer.six#59]
This is not a technical issue. It's more about increasing public trust in this repo and its organization.

- [ ] I've seen that [no members are listed](https://github.com/orgs/pdfminer/people) in the pdfminer organization. The [discussion that caused the creation of this organization](https://github.com/euske/pdfminer/pull/71#issuecomment-251045828) suggests that there are quite a few developers involved. Members, would you mind to make your organization status publicly visible? This should be possible at https://github.com/orgs/pdfminer/people

- [x] There is [no organization icon](https://github.com/pdfminer). That looks a bit sad. Can we come up with one and upload it to GitHub? e.g. [a modified version of what you find in a web search](https://duckduckgo.com/?q=pdfminer&t=canonical&iax=1&ia=images&iai=http%3A%2F%2Fmedia-cache-ak0.pinimg.com%2F736x%2Ffe%2F7d%2F3e%2Ffe7d3e177fe0e86d6643682acdeb9155.jpg), if the image license allows derivatives, or an actual [free PDF icon](http://findicons.com/search/pdf)

- [x] The description of the repository has French spelling (a space before the colon). Can this be fixed? e.g. replace "PDF Parser : fork with Python 2+3 support using six " by "Python PDF Parser -- fork with Python 2+3 support using six" on [the repo home](https://github.com/pdfminer/pdfminer.six).

**Comment by haydenc** [comment]
@bittner - that sounds like a very good idea, though it would be good to get clarity on the direction that @euske sees the project going in - in time surely the aim would be to merge forks together, either here or back on the main repo.

Currently it's a little hard to tell which repository i should be looking at, i've got a few problems with fonts and recursion issues that we've solved locally rather than get involved to this point.

Keen to get involved and help out where possible - this library is actually a big deal for us on a daily basis, so can justify spending quite a large amount of time.

**Comment by hughsw** [comment]
I've started using pdfminer.six for one of my clients, and I've been digging into the code as issues come up for me.  By and large the code is of high quality.  I've filed a couple of issues and and a couple of PRs.

Where are discussions about pdfminer.six happening?  I have some questions:
- Why are some PRs just sitting around?
- Is there any guidance on addressing Issues?
- This is my first exposure to `six`.  It's mildly intrusive for me, particularly now that Python 3 has considerable new syntax that just flows from my fingers...  Is there any talk of dropping Python 2 support?
- Is there any discussion of deeper or longer-term concerns (e.g. a way to avoid clustering work, as per this PR on the euske branch: https://github.com/euske/pdfminer/pull/91/files)?

Thanks for any insights.

**Comment by goulu** [comment]
@bittner : thanks for your suggestions. I just did what you proposed
@haydenc : @euske didn't want to merge .six with his repo last time we asked, but maybe he'll change his mind in the future... But please @haydenc if you corrected or enhanced anything, please just make a PR. If your branches passes the tests, I'll merge it.
@hughsw : right, I'm not very active myself anymore as pdfminer.six does what I needed, but I try to adress PR and issues about once per month (for example now...)

This is a small project maintained by occasional, opportunistic developers who needed pdfminer at some point. I don't think any of us has mid-term plans or objectives. I started pdfminer.six as I needed pdfminer to run under Python 3 and six seemed the simplest way to go. I don't know how many developers still use 2.7, but if you think a pdfminer.3 makes more sense, you're welcome to fork it and we'll be happy to host the fork in this group.

If any of you plans to invest some time in pdfminer, yu're most welcome to join the group. Thanks !

**Comment by pietermarsman** [comment]
I've just asked all members of the pdfminer organization to make their membership public. 

That solves this issue.

**Comment by pietermarsman** [comment]
@side2k, this is a message for you. I cannot find another way to reach you directly.

Since a few weeks I am part of the pdfminer organization and I am trying to get things going smooth again. 

One thing that was difficult for me (when I was not yet part of the github pdfminer organization) was to get to know who the maintainers are. Only Goulu is a public member of the organisation. To make it easier for people to reach us, members of the pdfminer organization, I would like to ask you to make your membership public.

See this link: https://github.com/orgs/pdfminer/people
