### ISSUE TITLE
Why extract_text function log automatically?

### ISSUE THREAD

**Issue by LawsonAbs** [pdfminer/pdfminer.six#608]
**Bug report**

- when I use the extract_text and logger that I defined at the same time, my logger will log the ouput of extract_text. the picture show detail information.

![image](https://user-images.githubusercontent.com/35190068/115665259-9d455580-a375-11eb-8e3b-382d7c60ed87.png)

Is this a bug?  I'm appriciate to you if you can solve this "problem"

**Comment by pedrounes1** [comment]
I faced this "issue" too. I set the root logger level to ìnfo`, because I use it to print out the progress of my code. Thus, when I use `extract_text` I get this logs too. 

I can think on two solutions: 
1) Open a PR to change `logging.info` to `logging.debug` , wich I think that is most appropriated;
2) Change my code (and your code, and everyone else's code that face this "issue") to use a local `logger`.

Right now, I changed my code to solve this, but I will open a PR to address this.
