### ISSUE TITLE
Error "Too many open files"

### ISSUE THREAD

**Issue by amlarraz** [pdfminer/pdfminer.six#627]
Hi,

We're using pdfminer.six to extract the text from a 100M documents. Due the documents quantity, we've launched 30 parallel instances of the same process, each one in working in a different and non-interesected documents batches. 
During some time, everything works perfectly but, suddendly appears a System Error:

`[Errno 24] Too many open files: <document path>`

And, all documents we will process from this moment throws same error.

Due the problem nature I can't reproduce the error, It happens when it happens ':)

We've tested our own code to debug our bugs but the error still appears. We've discovered that if we launch the process under windows there are no errors however in linux the error is the same all time. 

Our investigation leads us to a library error, concretely pdfminer error, we think there is some point in the code where with some pdfs the code gets stuck in a loop trying read something and reopen a non-closed file.

Any thoughts?? Many thanks in advance!

**Comment by pietermarsman** [comment]
Hard to investigate with more specific info.

Pdfminer.six does not open files in a loop. It opens and closes the file only once. 

If you do the file handling yourself, make sure that you close files properly. Even if the PDF parsing raises an error. If you use the high-level functions from pdfminer.six it will always close the file because it uses a context manager.
