### ISSUE TITLE
Strange behaviors while capturing LTChars

### ISSUE THREAD

**Issue by EmanueleGusso** [pdfminer/pdfminer.six#639]
Hi everybody,
First of all thank you and congratulations for this wonderful work.
I go straight to the point: with PDFMiner I can get the LTChar of a pdf document but I've noticed some strange behaviors (regardless of LTAnno objects that can be added):

1.  if in my doc I write, for example, a bulleted list, PDFMiner captures an LTChar(' ') when I haven't actually typed a space. Or sometimes it caputres an LTChar('\t') but still I haven't typed it.
2.  if in my doc I actually type \t, PDFMiner does not capture that corresponding LTChar and doesn't see \t at all.

So, my question is: aren't LTChar supposed to represent characters that I've actually typed? If not, what am I missing? Is it normal to have an "unpredictable" behavior when dealing with spaces or tabs?
I thank you all in advance for your availability!

**Comment by tadeoos** [comment]
Probably related to #281

**Comment by pietermarsman** [comment]
I expect you use word or some other text editor to generate the PDF's. I expect they insert spaces and tabs into the PDF, for whatever reason. 

The `LTChar`s that pdfminer.six extracts are defined in the PDF, and not inserted for some reason. All the inserted characters that are not in the original PDF are `LTAnno`. 

Closing this because question answered. Feel free to comment if you have more questions on this subject or willing to share the PDF in question.
