### ISSUE TITLE
Null character (\x00) when extract text 

### ISSUE THREAD

**Issue by datdao1998** [pdfminer/pdfminer.six#728]
Here I had a pdf file like this
[sample.pdf](https://drive.google.com/file/d/16T2eUyIDjHnkjlMdMeSwFDh7AZb5LYQ8/view?usp=sharing)

And here is my code 
```
from pdfminer.high_level import extract_pages
path = 'sample.pdf'
for page_layout in extract_pages(path):
    for element in page_layout:
        print(element)
```

But when I debug, I get some '\x00' characters (like image bellow), so when I encode to utf-8 format, they are NULL characters. 

![image](https://user-images.githubusercontent.com/42546396/158569490-d5850d8d-1590-4ad7-a642-2606cd41f037.png)

I think the reason for that is the difference of encodings, but I can't find good solutions for it. I want to read all text of my pdf in utf-8 format (in this case, '\x00' is actually 'ti' in utf-8, and I want to parse it to read correctly).

**Comment by pietermarsman** [comment]
It is a problem with your PDF that pdfminer.six (or any PDF reader) cannot solve. If you copy the text in question you get:

```
(Quan
ty)
```

Note that the `ti` in the middle is missing. 

You can read the text because a PDF has separate representations for the glyphs (what you see) and there utf-8 interpretation (what pdfminer.six extracts) of those glyphs. In this case the utf-8 representation is wrong.

**Comment by datdao1998** [comment]
Thanks for your quick answer. It's really helpful.
