### ISSUE TITLE
Can't get the correct text object matrix

### ISSUE THREAD

**Issue by Beants** [pdfminer/pdfminer.six#738]
**Bug report**
### A description of the bug
* This bug is specifically: the result of matrix are wrong, and the matrix are below the correct coordinates;
* This bug may appear in Chinese documents and may also appear in English documents;
* Due to non-disclosure agreement, I can't give you the original file, but can provide some pictures and original data；
### How can i find this bug
* Use The "Preview.app" in mac to open this file, you can see some special phenomena: when I want to select "and Technology", a box with an incorrect height will appear, and the lower border matrix of this box is  The lower boundary parsed by pdfminer.six
* file image is ![file image](https://s2.loli.net/2022/03/23/Ljtp2scRmZJPOXU.png)
* original data:![original data](https://s2.loli.net/2022/03/23/rCjgzGqvdpB73Ds.png)
## My attempt
* I changed code1 to code2 and got the correct coordinates

**code1**:pdfminer/layout.py:376
```python
bbox_lower_left = (0, descent + rise)
bbox_upper_right = (self.adv, descent + rise + fontsize)
```
**code2**:pdfminer/layout.py:376
```python
bbox_lower_left = (0, 0)
bbox_upper_right = (self.adv,  fontsize)
```
### My Question
* So I want to know which matrix do you want? Is it the matrix of the text or the matrix of the border box(like in the pic before)? and how to got the right matrix of the text object?
* Please indicate if you need more data
* Thanks a lot!

**Comment by pietermarsman** [comment]
This is due to an error in your PDF. It specifies a fontsize of 209 (very big) and a descent of -514 (also very big). The big font size can be seen with the osx preview app. I don't know why it does not also descent (lower) the bounding box, maybe it is ignoring the descent because it is so massive. 

Anyway, the primary reason for the bounding boxes being off is that this is how the PDF has encoded it. 

Unless the actual descent value extracted from the PDF should not be -514. But that is impossible to tell without having the actual document. 

Feel free to open a new issue if you can replicate this with a PDF that you can share.
