### ISSUE TITLE
can pdfminer.six be installed by debian apt-get tools?

### ISSUE THREAD

**Issue by zffocussss** [pdfminer/pdfminer.six#745]
Hi team:
  I am not a python developer, but an operator. our application code is running on Debian os.can pdfminer be installed by "apt-get install python3-pdfminer".if it is possible, what's the difference between pip install and apt-get install?

**Comment by pietermarsman** [comment]
It certainly seems like it: https://tracker.debian.org/pkg/pdfminer

But that is not something I was aware of. 

It is maintained by the Debian Python Team, that sounds trustworty. Also the testing and unstable version are in sync with the latest release, so that's good. 

If you just need the _pdf2txt.py_ functionality I guess this is a fitting way to install the package.
