### ISSUE TITLE
Files with "one line dictionaries" not parsed correctly

### ISSUE THREAD

**Issue by armijnhemel** [pdfminer/pdfminer.six#750]
There are quite a few files (example: https://raw.githubusercontent.com/adobe/xmp-docs/master/XMPSpecifications/XMPSpecificationPart3.pdf ) where everything in a dictionary is on a single line and not one line per key/value. I looked at the PDF specifications ( https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf ), specifically the definition of dictionaries (section 7.3.7) but to my surprise I couldn't find anything about a dictionary item needing to be on a separate line to comply with the PDF standard.

An example (from the XMP specifications part 3 file):

```
<</Size 3476/Prev 706391/Root 3334 0 R/Info 3332 0 R/ID[<3DBD06474EAFA4AEFBB02CCC8C371F26><3B8636EF4DDDA240902C38D50D2ACFE6>]>>
```

**Comment by pietermarsman** [comment]
These dictionary objects are not parsed correctly because of the lack of white space. Section 3.1.1. (Character Set) of the [PDF reference](https://ghostscript.com/~robin/pdf_reference17.pdf) specifies that seperate syntactic constructs such as names and numbers must be separated by a white space. 

In your case the `/Size` key is `3476/Prev`. In this anomaly document the `/Prev` should be a new key, but we cannot change the way this is handled because it would introduce issues with other (valid) document.

So unfortunately not much that can be done to improve this.
