### ISSUE TITLE
[Performance] Using multiprocessing to accelerate PDF processing

### ISSUE THREAD

**Issue by tristone13th** [pdfminer/pdfminer.six#758]
**Feature request**

Using multiprocessing to accelerate PDF processing.

For instance, when we process large PDF files, the loading process is long. Can we use multiprocessing in python to accelerate this? after some investigation, I have some options:
 - native multiprocessing mechanism;
 - joblib
 - ray

Due to the existing GIL in Python, we cannot use multithreading to achieve this.

**Comment by tristone13th** [comment]
> I would recommend processing pages in parallel.
> 
> A PDF document is basically a list of objects stored in a blob. A page object is a hierarchy of those objects and determines how and where text is rendered.
> 
> With pdfminer.six you can detect the number of pages without doing any of the advanced processing. Then you can create jobs to process each of the pages in parallel.
> 
> We wont include explicit support for parallel processing since this is already possible with the composable api and some custom orchestration code.

It is possible, but it's tricky to implement it. 

As you know, CPython has GIL, so using multi-threading is not helpful.

If we use multi-processing, the objects in pdfminer.six are inter-linked each other, which means it's not easy to serialize them and passing them between processes, which means solutions like `pool.map` will always throw out a serialization error: the pickle thing.

So is it possible to provide a multiprocessing mechanism in the source code which can invoked by the user, rather than let the user to implement it?

**Comment by pietermarsman** [comment]
> As you know, CPython has GIL, so using multi-threading is not helpful.

Have you tried? This is an assumption worth testing. 

> If we use multi-processing, the objects in pdfminer.six are inter-linked each other, which means it's not easy to serialize them and passing them between processes, which means solutions like pool.map will always throw out a serialization error: the pickle thing.

The only thing you need to communicate is the path of the pdf file and the page you want to process. The process can read the file from disk and extract the text from the specified page.

PDF is built in such a way that you don't need to read the entire byte stream in order to process a particular page. It can read all relevant objects and ignore the rest. That's what pdfminer.six will provide you with out of the box if you ask it to extract text from a specific page only.
