### ISSUE TITLE
Dependency (typing_extensions) requires python 3.7, pdfminer is said to require python 3.6

### ISSUE THREAD

**Issue by nicofrand** [pdfminer/pdfminer.six#762]
Hi,

First, thanks for the hard work!

pdfminer.six says it requires python 3.6 at least but uses typing_extensions here: https://github.com/pdfminer/pdfminer.six/blob/617e4c8388fa61ed68b8ff450c48f79e41102be6/pdfminer/image.py#L10, which requires python 3.7+: https://pypi.org/project/typing-extensions/.

So, I think pdfminer should say it requires python3.7 at least?

Regards

**Comment by hydrargyrum** [comment]
I would add that typing-extensions is not optional for installing pdfminer.six in python3.7, so it should be a hard requirement on this version, like this: `typing_extensions; python_version < "3.8"` (this specifies that the requirement has a condition)

**Comment by pietermarsman** [comment]
Initially I thought you were right. 

But it turns out typing-extensions can also be installed on 3.6. The version 4.1.1 supports Python 3.6. 

![image](https://user-images.githubusercontent.com/3833456/175788365-ab7e328b-85eb-4046-86d3-1fd880a8515e.png)

Our github workflow will ensure that all usages of typing-extensions will be available in Python 3.6. 

Feel free to open a new issue if you have a specific problem with installing or using typing-extensions in combination with pdfminer.six.

**Comment by hydrargyrum** [comment]
@pietermarsman if using python 3.7 (or 3.6) pdfminer.six does require typing-extensions, it's not optional. So it should be clearly stated in the requirements, like this: `typing_extensions; python_version < "3.8"`

**Comment by pietermarsman** [comment]
Ah, I see now.
